version: "3.9"
services:
  web:
    build: .
    ports:
      - "8390:8080"
    networks:
      - project_network

  # Use root/example as user/password credentials
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: example
    networks:
      - project_network
    volumes:
      - flaskauth_mariadb:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8392:8080
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  flaskauth_mariadb:
    external: true